site_name: WiFiCom Docs
theme:
  name: material
  palette:
    primary: red
markdown_extensions:
- attr_list
- md_in_html
nav:
    - Introduction: 'index.md'
    # - 'about.md'
    # - 'resources.md'
    - 'buy_premade.md'
    - 'Build Your Own':
        - 'diy_build.md'
        - 'parts_list.md'
        - 'picow_breadboard.md'
    # - 'onboarding_wificom.md'
    # - 'credentials.md'
    # - 'configuration.md'
    # - 'editable_files.md'
    - 'device_user_guide.md'
    - 'apps.md'
    - 'w0rld_integration.md'
    # - 'realtime_battles.md'
    # - 'power_options.md'
    - 'upgrading_software.md'
    # - 'troubleshooting.md'
    - 'dependencies.md'
    - 'credits.md'
