site_name: WiFiCom Docs
theme:
  name: material
  palette:
    primary: red
markdown_extensions:
- attr_list
- md_in_html
nav:
    - Introduction: 'index.md'
    - Videos: 'videos.md'
    - 'Get a WiFiCom':
        - 'buy_premade.md'
        - 'Build Your Own': 'diy_build.md'
        - 'parts_list.md'
        - 'picow_breadboard.md'
        # - 'power_options.md'
    - 'Device Guides':
        - 'device_setup.md'
        - 'device_user_guide.md'
        - 'config_files.md'
        - 'troubleshooting.md'
        - 'manual_install.md'
    - 'Apps':
        - 'app_list.md'
        - 'app_setup.md'
        - 'w0rld_integration.md'
        - 'realtime_battles.md'
    - 'credits.md'
